#!/usr/bin/env python3
"""Generate the navigation strips at the top and bottom of every guide.

Each guide in Getting-Started/ carries a strip like this:

    [<- Previous Guide](./02-previous.md) . **This Guide** . [Next Guide ->](./04-next.md)

    `########....` 33% of the way through

Both strips are generated from the guide filenames and their `# ` titles,
so adding, renaming, or retitling a guide only means re-running this
script. Do not edit the strips by hand: the next run overwrites them.

    python3 scripts/build-nav.py            # rewrite the strips
    python3 scripts/build-nav.py --check    # fail if they are out of date

The --check mode is what runs in CI, so a pull request that adds a guide
without regenerating gets told about it instead of merging a broken
"next" link.
"""

import glob
import os
import re
import sys

GUIDE_DIR = "Getting-Started"
GUIDE_GLOB = "[0-9][0-9]-*.md"

# The index a reader lands on if they step back off the front of the course,
# and where they go on after the final guide.
BEFORE_FIRST = ("Start here", "../README.md")
AFTER_LAST = ("How-To Guides", "https://community.codetopia.org/howtos")

# Progress bar. One cell per guide, so the bar fills up exactly as the
# course does. Both characters are the same width in a monospace font,
# which is why the strip sits inside backticks.
CELL_FULL = "▓"
CELL_EMPTY = "░"

TOP_OPEN, TOP_CLOSE = "<!-- nav:top -->", "<!-- /nav:top -->"
BOTTOM_OPEN, BOTTOM_CLOSE = "<!-- nav:bottom -->", "<!-- /nav:bottom -->"
WARNING = "<!-- Generated by scripts/build-nav.py. Do not edit by hand. -->"

# A header we are willing to replace: either a previously generated strip or
# the older hand-written `---` / `Guide 01 of 12` pair. Anything else in front
# of the title is real content and the script refuses to touch the file.
LEGACY_HEADER = re.compile(
    r"\A(?:---\s*|Guide \d+ of \d+\s*|\[?&?larr;?.*|`[▓░]+`.*|\s*)\Z"
)


def read(path):
    with open(path, encoding="utf-8", newline="") as fh:
        text = fh.read()
    return text, ("\r\n" if "\r\n" in text else "\n")


def guides():
    paths = sorted(glob.glob(os.path.join(GUIDE_DIR, GUIDE_GLOB)))
    if not paths:
        sys.exit(f"No guides found in {GUIDE_DIR}/ matching {GUIDE_GLOB}")
    found = []
    for path in paths:
        text, _ = read(path)
        match = re.search(r"^# (.+?)\s*$", text, re.M)
        if not match:
            sys.exit(f"{path} has no `# Title` heading, so it cannot be linked to.")
        found.append((path, match.group(1)))
    return found


def link(label, href):
    """A Markdown link, or the anchor form for external ones.

    House style opens external links in a new tab so a reader never loses
    their place in the course. Links to files in this repo stay plain
    Markdown.
    """
    if href.startswith(("http://", "https://")):
        return (f'<a href="{href}" target="_blank" '
                f'rel="noopener noreferrer">{label}</a>')
    return f"[{label}]({href})"


def strip(index, entries, newline):
    """The one-line prev / position / next strip for guide `index`."""
    total = len(entries)

    if index == 0:
        label, href = BEFORE_FIRST
    else:
        prev_path, label = entries[index - 1]
        href = "./" + os.path.basename(prev_path)
    back = link(f"← {label}", href)

    if index == total - 1:
        label, href = AFTER_LAST
    else:
        next_path, label = entries[index + 1]
        href = "./" + os.path.basename(next_path)
    forward = link(f"{label} →", href)

    # The middle of the strip is the guide you are on, named rather than
    # numbered, to match how the rest of the docs refer to guides. The file
    # numbers exist to sort the files, not to be read.
    # Progress is a percentage so there is never a competing count.
    filled = index + 1
    bar = CELL_FULL * filled + CELL_EMPTY * (total - filled)
    percent = round(filled * 100 / total)

    return (
        f"{back} · **{entries[index][1]}** · {forward}{newline}"
        f"{newline}"
        f"`{bar}` {percent}% of the way through"
    )


def render(path, index, entries):
    text, newline = read(path)
    body = strip(index, entries, newline)

    top = newline.join([TOP_OPEN, WARNING, body, TOP_CLOSE])
    # The bottom strip repeats the links without the bar: by then the reader
    # wants the controls, not the progress reminder.
    bottom = newline.join(
        [BOTTOM_OPEN, WARNING, "---", "", body.split(newline)[0], BOTTOM_CLOSE]
    )

    text = replace_top(path, text, top, newline)
    text = replace_bottom(text, bottom, newline)
    return text


def replace_top(path, text, top, newline):
    block = re.compile(
        re.escape(TOP_OPEN) + r".*?" + re.escape(TOP_CLOSE), re.S
    )
    if block.search(text):
        return block.sub(lambda _: top, text, count=1)

    title = re.search(r"^# .+$", text, re.M)
    if not title:
        sys.exit(f"{path} has no `# Title` heading.")

    header = text[: title.start()]
    if not all(LEGACY_HEADER.match(line) for line in header.split(newline)):
        sys.exit(
            f"{path} has content above its title that this script does not\n"
            f"recognise, so it will not overwrite it. Move that content below\n"
            f"the title, or add the {TOP_OPEN} / {TOP_CLOSE} markers by hand."
        )
    return top + newline * 2 + text[title.start():]


def replace_bottom(text, bottom, newline):
    block = re.compile(
        re.escape(BOTTOM_OPEN) + r".*?" + re.escape(BOTTOM_CLOSE), re.S
    )
    if block.search(text):
        return block.sub(lambda _: bottom, text, count=1)
    return text.rstrip(newline + " ") + newline * 2 + bottom + newline


def main(argv):
    check = "--check" in argv
    entries = guides()
    stale = []

    for index, (path, _) in enumerate(entries):
        current, _ = read(path)
        updated = render(path, index, entries)
        if current == updated:
            continue
        stale.append(path)
        if not check:
            with open(path, "w", encoding="utf-8", newline="") as fh:
                fh.write(updated)

    if check and stale:
        print("These guides have out-of-date navigation strips:\n")
        for path in stale:
            print(f"  {path}")
        print("\nRun this, then commit the result:\n")
        print("  python3 scripts/build-nav.py\n")
        return 1

    if check:
        print(f"Navigation is up to date across {len(entries)} guides.")
    else:
        print(
            f"Rewrote {len(stale)} of {len(entries)} guides."
            if stale
            else f"Already up to date across {len(entries)} guides."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
